add error run feature
Recently I had some issues with one of my cronjobs that need internet
connection in order to work. The problem was that it seems like awecron
sometimes started before internet connection was established. As the
result of this it exits with exit code 0, but it was not actually
successful. This simple feature is supposed to allow setting it to
exit with a special exit code that will re-run the cronjob after smaller
interval. The feature is not standard, but it is still fairly minimal.

diff --git a/awecron b/awecron
--- a/awecron
+++ b/awecron
@@ -19,11 +19,15 @@ main ()
         rm "$d/tmr"
         # gets the cronjob configuration variables
         source "$d/cfg"
-        # runs the binary with specified user and then sets the timer if exit code is 0
+        # runs the binary with specified user
           # Note: su part prevents code injection
-        su "$user" -s /bin/sh -c '"$1"' awecronrun "$d/run" && touch -d "@$(( time + intrv ))" "$d/tmr"
+        su "$user" -s /bin/sh -c '"$1"' awecronrun "$d/run" && \
+          # sets the timer if exit code is 0
+          ec=$? && touch -d "@$(( time + run ))" "$d/tmr" || \
+          # OR checks for ercode match and sets errun interval
+          ec=$? && [[ "$ec" == "$ercode" ]] && touch -d "@$(( time + errun ))" "$d/tmr" 
         # logs events
-        printf "awecron %s: %s [%s]\n" "$user" "$name" "$?"
+        printf "awecron %s: %s [%s]\n" "$user" "$name" "$ec"
       fi
     )
 	done	
